### ISSUE TITLE
Critical error with WP installs not on the domain root

### ISSUE THREAD

**Issue by ryanhellyer** [bkirby989/WallaceTheme#10]
I'm not sure if there are missing instructions, or if the theme is just broken. I tried using it, but the home page just redirects back to the root of the domain and the inner pages are throwing a lot of JS errors, and a square box at the top of the page links to the root of the domain too.

**Comment by bradleykirby** [comment]
Hey Ryan, sorry about the error. It does look like some people are experiencing errors on installation. If you could answer a few questions it would be really helpful to in me diagnosing what's going wrong here. 

1. What, if any, PHP errors are you getting?
2. What are the JS errors you mentioned?
3. What is your permalink structure set to?
3. What version of WordPress are you using? Are the rest api endpoints enabled? (try /wp-json/wp/v2/posts to be sure)
5. What host are you using, or is this a local setup? 

Additionally if you have a public link to the site that's throwing the errors that would be helpful for me to look at as well. 

Thanks, and I'll try to get this fixed ASAP.

**Comment by ryanhellyer** [comment]
^ I'll ignore the questions until I point what I think is triggering it (I haven't checked though).

My local setup is a sub-folder multisite installation. So the root URL for the site is http://dev.hellyer.kiwi/wallace/. Your theme seems to be assuming that the root of the site is http://dev.hellyer.kiwi/.

Perhaps it only works when the home URL is the root of the domain?

**Comment by bradleykirby** [comment]
Ah, that's certainly possible. I've only tested on sub-domain multisite installs. Thanks for identifying that. I'll set up a sub-folder install locally to reproduce.

**Comment by ryanhellyer** [comment]
Oh yeah, look, you have set a base URL with the base set to the root. You can't do that in WordPress themes or the sky will fall on your head ;)

https://github.com/bkirby989/WallaceTheme/blob/master/header.php

**Comment by bradleykirby** [comment]
Can certainly see how that'd be a problem with sub-folder multisites. I'll try to get a fix out tomorrow. Thanks for the report @ryanhellyer

**Comment by bradleykirby** [comment]
@ryanhellyer when you get a chance can you see if the latest release (v1.0.1) fixes your issue? An update should now be available directly on your install.

**Comment by bradleykirby** [comment]
When I reproduced the issue it was the client side routing system, rather than the base tag, that was causing the problems, so I've left the base tag in for now. But feel free to reopen if there's still a problem and i'll take another look.

**Comment by ryanhellyer** [comment]
When I visit the home page, it loads, but a second later it redirects to the domain root.

**Comment by bradleykirby** [comment]
You're on version 1.0.1?

**Comment by ryanhellyer** [comment]
No, it updated to Version 1.0.0.

**Comment by bradleykirby** [comment]
Possible that something went wrong with the updater then. Downloading a fresh copy from wallacetheme.com should give you 1.0.1
