### ISSUE TITLE
templates do not work on smartOS

### ISSUE THREAD

**Issue by raininja** [bkirby989/WallaceTheme#15]
[root@b9a5f77b-fbaa-45b7-a775-938bc76ada64 ~]# uname -a
SunOS b9a5f77b-fbaa-45b7-a775-938bc76ada64 5.11 joyent_20151112T052215Z i86pc i386 i86pc

not going to lie, it may just be my configuration because I really have a kludgy kind of setup going on here, although I have the same behavior on my arch linux machine

[raijin@ishtar][~]%uname -a
Linux ishtar 4.10.2-4-ck #1 SMP PREEMPT Tue Mar 14 19:42:40 EDT 2017 x86_64 GNU/Linux

you can see what I mean at http://denki.ninja

http://denki.ninja:8080/phpinfo.php

Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /opt/local/www/denki.ninja/wp-content/themes/WallaceDist/footer.php on line 2

it's on, however

**Comment by bradleykirby** [comment]
Hey thanks for the report,

http://denki.ninja seems to be working correctly for me, both with js enabled and without. Maybe it was a local caching issue?

If you're still experiencing an issue, what do you mean exactly by the "templates do not work"? Are you seeing just a blank screen?

**Comment by raininja** [comment]
I see what's going on here.  This is a simple blog theme and you have not implemented any of the other of that page types, or menus or anything. . . but I do see that you have implemented "The Loop" in javascript, which is something that I have been searching for.  Now we need to implement the rest of the stuff that The Loop normally uses. . .  Nevermind! Closing and forking.

**Comment by raininja** [comment]
thanks for your work, by the way

**Comment by bradleykirby** [comment]
Of course! Thank you! Look forward to seeing what you do in the fork.
