### ISSUE TITLE
accesing post url directly showing white screen

### ISSUE THREAD

**Issue by kdpuvvadi** [bkirby989/WallaceTheme#7]
After install the theme and activation, i can access posts from homepage but if i access the url directly it showing blank page,

**Comment by bradleykirby** [comment]
Thanks for the report. Are you using WordPress version 4.7 with pretty permalinks?

**Comment by kdpuvvadi** [comment]
yes, i'm using version 4.7

**Comment by kdpuvvadi** [comment]
and i've come to know that it is also happening on you demo site also

**Comment by bradleykirby** [comment]
Hmm, is there a console error or php error you're getting? I'm currently unable to reproduce this.

**Comment by bradleykirby** [comment]
What version browser are you using?

**Comment by bradleykirby** [comment]
Likely a dup of #10

**Comment by bradleykirby** [comment]
Feel free to reopen this if 1.0.1 hasn't solved it.
