### ISSUE TITLE
Menu support

### ISSUE THREAD

**Issue by benhartwich** [bkirby989/WallaceTheme#8]
Hi,

would be great, if your theme would support a main menu.

**Comment by bradleykirby** [comment]
I agree, will look at doing this when adding in support for pages.

**Comment by benhartwich** [comment]
Great, let me know if you need localisation support for german.

**Comment by bradleykirby** [comment]
Will do, thanks!

**Comment by smoscar** [comment]
Hey man,

I added support for a main menu on the following commits:

https://github.com/smoscar/WallaceTheme/commit/e3bf729e12b85cf0a8baac5e1990e719894efa03
https://github.com/smoscar/WallaceTheme/commit/4717c19276361b5d2c011cf615675449745ad7ff

Note: For now it only supports a one level menu

**Comment by benhartwich** [comment]
Thanks, works great! But it is only available on home page not on single pages.

**Comment by smoscar** [comment]
Yes, I didn't want to change the theme structure that much, but the components and routes needed are already being loaded on both pages and posts so it should be fairly easy to show the views on every page
